### PR TITLE
Updated use to match PHPUnit change

### PR DESCRIPTION
**Pull request by krazzer**

### CODE REVIEW

**Comment by Naktibalda** [comment]
@krazzer Could you provide a link to description of PHPUnit change?
Is this change required for compatibility with PHPUnit 9?
In that case we will only need to care about it when PHPUnit 9 is released,
currently `codeception/stub` must work with PHPUnit 6, 7 and 8.

**Comment by krazzer** [comment]
@Naktibalda https://github.com/sebastianbergmann/phpunit/commit/7f664ffd558ba68031963f63d3e23a951ba441fc#diff-3f7646d228a0775c3aa74d1312359786

**Comment by Naktibalda** [comment]
Thanks, I will leave this pull request open and consider merging it when the tests start failing.

**Comment by W0rma** [comment]
Seems like the change found its way into phpunit 8.4.0 which was released today

**Comment by Naktibalda** [comment]
Yes, it broke the build: https://travis-ci.org/Codeception/Codeception/jobs/592949059
And this change wasn't even mentioned in the changelog: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-8.4.md

**Comment by Naktibalda** [comment]
Please add this version constraint `"phpunit/phpunit": "8.3.*" to your composer.json to prevent automatic upgrade to PHPUnit 8.4

**Comment by W0rma** [comment]
Related issue at phpunit: https://github.com/sebastianbergmann/phpunit/issues/3880

**Comment by krazzer** [comment]
The directories are now renamed in PHPUnit: https://github.com/sebastianbergmann/phpunit/issues/3880

Which makes more sense. I guess this will be updated in 8.4.1 so I'm closing this as it might do more harm than good

**Comment by Naktibalda** [comment]
As Sebastian wrote, directory name wasn't an issue, please update Expected class too.

**Comment by Naktibalda** [comment]
Released as [3.5.0](https://github.com/Codeception/Stub/releases/tag/3.5.0)

**Pull request closed without merging**
